# Site
# repository: sproogen/resume-theme
favicon: images/icon.png

# Personal info
name: João Pedro
full_name: João Pedro Moreira Ferreira
title: Personal
position: Computer Vision M.Sc Student
# email: joaopmoferreira@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
scholar: citations?user=QacWVbEAAAAJ&hl=pt-BR&oi=sra
lattes: 0866273910879686
github_username:  jpeumesmo
linkedin_username: jo%C3%A3o-pedro-moreira-ferreira-165a91154
research_gate: Joao_Ferreira144
cv: assets/cv.pdf
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
# about_profile_image: images/profile2.jpg
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is João Pedro and I am a Master's student in Computer Vision and Machine Learning. I'm currently working on <mark><a href="https://en.wikipedia.org/wiki/Generative_adversarial_network"><font color="white">GAN's</font></a></mark> and <mark><a href="https://tkipf.github.io/graph-convolutional-networks/"><font color="white">GCN's</font></a></mark>. I worked as a developer during undergraduate degree solving issues on web systems and the infrastructure of the distance education nucleus of the university. During my career, I have worked with different teams on several projects and it has given me experience in teamwork and Agile software development.

  I am most skilled in: <mark>Computer Vision</mark> and <mark>Machine Learning</mark>
  
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false
# darkmode: true
# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins_dir:
 - jekyll-seo-tag

# gtag: UA-149430375-1
gtag: G-MG3J0MLQYT